### ISSUE TITLE
Team Assignment

### ISSUE THREAD

**Issue by zlw5009** [zlw5009/pair-up#10]
- Link on project to team assignment display list
- Link to FAQ and Blog for working in a team
- List displays teams by email
- Captain is listed first with icon
- Current users team is highlighted
- Database randomly assigns teams a 00:00 on the start date of the project
  Algorithm Logic
- Total amount of players signed up for the project
- Divide total by 4 - If remainder is less than 3, divide total by 3
- Team sizes should be equal at 2-4 users per team
- User with most project history is assigned Captain

**Comment by zlw5009** [comment]
**User Experience/Use Case:**
How user will interact with this feature:
At midnight of the start date for a project, the teams will be automatically assigned. On the project page, there will be a link to team assignments. All teams will be displayed with the _current user_'s team highlighted. Each team member's email will be displayed so the current user can contact their team. The Team Captain/Leader will be listed first in the team list with an icon to designate the team leader. 

External links will include redirects to the blog for team collaboration advice as well as FAQ. 

**Factors:**
- Two users must signup for a project for the project to continue. 
- If a team drops below two users, the remaining user must be redistributed to a team.
- Teams assigned and displayed at midnight of the challenge start date

**Backend:**
- Divide total players signed up by 4 - if remainder is greater than 0 and less than 3, divide total by 3. No team should have more than 1 extra player compared to all other teams. (Ex. There shouldn't be 1 team of 2 users and 3 teams of 4 users.) 
- User with most projects completed is designated captain.

**Comment by ghost** [comment]
Maybe a user should have the option to be reassigned to a team or continue on their own instead of forcing it on them.
