### ISSUE TITLE
Team Submission

### ISSUE THREAD

**Issue by zlw5009** [zlw5009/pair-up#11]

**Comment by MichaelrMentele** [comment]
**User Experience/Use Case:
How user will interact with this feature:**
A team leader can enter a submission link on the current challenge page. This can be modified up until the closing date specified in #8 , after the closing date submissions are accepted but are not eligible for ranking, merely participation.

**How to implement via backend**
- Basic table update to submission link column for a team.
- Render this link to the index of teams for a project

See wireframes.

**Comment by zlw5009** [comment]
Good!
