### ISSUE TITLE
Admin Moderating

### ISSUE THREAD

**Issue by zlw5009** [zlw5009/pair-up#13]
- Adding Challenges
- Delete Challenges
- Edit Challenges

**Comment by zlw5009** [comment]
User Experience/Use Case:
How user will interact with this feature:
Admin will have a dashboard that gives access to creating a new project, deleting a project, and editing a project. 

**Factors:**
- New project -> Title, Description, External links to source code/preview, skills/exp required.
- If challenge is deleted, all users/teams disbanded. 
- Designated admin login

**Comment by ghost** [comment]
Do we need a seperate login for admins? They can login with the same form as users and if they're an admin then we can just show them the extra actions on their dashboard (creating projects and such).
