### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by zlw5009** [zlw5009/pair-up#14]

**Comment by MichaelrMentele** [comment]
**User Experience/Use Case:**
**How user will interact with this feature:**
Related to login, please see that issue. A user may choose to register. They will be presented with the choice of using an email and password log in OR using OAuth via Github. Once a user is registered they are automatically logged in.

**Factors**
- Username must be unique
- Password must be [4 characters] minimum

**Edge Cases**

**How to implement via backend**
- OAuth for Github
- Bcrypt-ruby gem for custom authentification
- Store current user in session hash
- Use global helpers to turn on and off functionality in views
- User before action in routes to bypass routes
- Cache current user data object for logged_in? method

**Comment by zlw5009** [comment]
Michael, this will probably be better for User Authentication. User Registration will be more along the lines of the registration form. This should be where the user adds their skills/experience.

**Comment by ghost** [comment]
What does the line "User before action in routes to bypass routes" mean here?

**Comment by zlw5009** [comment]
Set up form after user entered credentials for sign up
