### ISSUE TITLE
General Layout for pages

### ISSUE THREAD

**Issue by MichaelrMentele** [zlw5009/pair-up#22]
Header
Navbar

**Comment by MichaelrMentele** [comment]
Just added sitewide links for clicking around.

**Comment by MichaelrMentele** [comment]
Only dynamic route is users and that is hardcoded for now.

**Comment by zlw5009** [comment]
Navbar needs a home link. We can just put home for now but eventually it'll be a logo. 
- This will have to be redirected to landing page unless user is logged in, then it'll redirect them to their dashboard.
