### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by zlw5009** [zlw5009/pair-up#5]
Ideas?

**Comment by MichaelrMentele** [comment]
Using bycrpt-ruby it is relatively simple to implement a one-way hashing for passwords. This is the standard. We implement basic sign on with email and password and have Github integration as a stretch goal.

**Comment by zlw5009** [comment]
That works. I found a gem called Warden for authentication and it utilizes BCrypt.

**Comment by zlw5009** [comment]
**User Experience/Use Case:**
How user will interact with this feature:
Relates to Login feature; User will be required to enter "Email" and "Password" upon signup or have the option to utilize Github SSO. This request will be performed during login as well.

**Factors**
- Check if username exists -> must be unique
- Password between 8-25 characters long with 1 char & 1 number minimum

**Backend**
- Omni-Auth for Github SSO
- BCrypt password hashing
- If sign up -> Redirected to User Registration Form (See issue for details)

**Comment by MichaelrMentele** [comment]
I've tried warden before and found it more cumbersome than using bcrypt
alone.

**Comment by ghost** [comment]
+1 for bcrypt. We should implement the most simple authentication first, make sure it works then we can work our way towards SSO

**Comment by zlw5009** [comment]
User Experience/Use Case:
How user will interact with this feature:
Related to login, please see that issue. A user may choose to register. They will be presented with the choice of using an email and password log in OR using OAuth via Github. Once a user is registered they are automatically logged in.

Factors

Username must be unique
Password must be [4 characters] minimum
Edge Cases

How to implement via backend

OAuth for Github
Bcrypt-ruby gem for custom authentification
Store current user in session hash
Use global helpers to turn on and off functionality in views
User before action in routes to bypass routes
Cache current user data object for logged_in? method
