### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by zlw5009** [zlw5009/pair-up#7]

**Comment by MichaelrMentele** [comment]
**User Experience/Use Case:**
**How user will interact with this feature:**
A user can read about, watch a video overview of, and sign up for an upcoming project. Once signed up a user can download: a suggested team format, stub code, and stub ERD.

**Factors**
- An upcoming project will be released on the [15th] of every month
- A new project needs a minimum of [2] people

**Edge Cases**
- Not enough users for a new project, project is canceled.

**How to implement via backend**
Suggest an ORM via datamapper or other to wrap models.
See wireframes.

**Comment by zlw5009** [comment]
A new project minimum should be designated to [2] users. Other than that I think this is good.
