### ISSUE TITLE
Current Project

### ISSUE THREAD

**Issue by zlw5009** [zlw5009/pair-up#8]

**Comment by MichaelrMentele** [comment]
**User Experience/Use Case:
How user will interact with this feature:**
A user can navigate to the active project page. There she can read a brief overview and view the teams and their status. A user can also click through to read about, watch a video overview of the current project. If a user is signed up for the project she can download: a suggested team format, stub code, and stub ERD. A team leader can make a project submission [posting a link] to the current project page for his team.

**Factors**
- A current project ends on the [25th] of every month.
- A current project is submitted by a team leader before the [25th]
- If a project is not submitted on time it is disqualified from winning though it may still be submitted.
- After the submission cutoff users may vote on their favorite project.

**Edge Cases**
- The month  of February is short, therefore submissions should be required on the [23rd]

**How to implement via backend**
Suggest an ORM via datamapper or other to wrap models. Suggest a 'Sessions' controller to handle various state changes to the website. Ex. When a current project is ongoing and a new project is added for signup. And when a new project is moved to an active state and there is no upcoming project.
See wireframes.

**Comment by zlw5009** [comment]
I'm happy with this.
