### ISSUE TITLE
Past Projects

### ISSUE THREAD

**Issue by zlw5009** [zlw5009/pair-up#9]

**Comment by MichaelrMentele** [comment]
**User Experience/Use Case:
How user will interact with this feature:**
A user can navigate to a listing of past projects. A selected past project is identical to a current challenge page except that its state is frozen. It contains a team listing with final standings, and submissions for each team. A link to read about, watch a video overview of, and sign up for an upcoming project. A user can download: a suggested team format, stub code, and stub ERD.

**Factors**
- A user cannot modify data

**How to implement via backend**
Simple indexing and display of projects table packaged with the upcoming view and current view developed during the project pipeline.

See wireframes.

**Comment by zlw5009** [comment]
Good.
